### ISSUE TITLE
RemoteConfig isn't being fetched on iOS simulator

### ISSUE THREAD

**Issue by pr-Mais** [pr-Mais/noor#6]
**Describe the bug**
Once the app starts on iOS, it fails to fetch the remote config value in Home with following log:

```
flutter: [firebase_remote_config/internal] internal remote config fetch error
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
<asynchronous suspension>
#2      MethodChannelFirebaseRemoteConfig.fetchAndActivate
package:firebase_remote_config_platform_interface/…/method_channel/method_channel_firebase_remote_config.dart:145
<asynchronous suspension>
#3      RemoteConfig.fetchAndActivate
package:firebase_remote_config/src/remote_config.dart:86
<asynchronous suspension>
#4      RemoteConfigService.fetchNoorRC
package:noor/services/remote_config.dart:31
<asynchronous suspension>
#5      _AnimatedHeaderState._loadRemoteConfig
package:noor/…/1_home/home.dart:348
<asynchronous suspension>
```

**To Reproduce**
1. Run the app on iOS

**Phone:**
 - Device: iOS simulator
 - OS: iOS 14.5
 - App Version: 2.4.0

**Comment by YazeedAlKhalaf** [comment]
I haven't run the app but try checking the Google Cloud Console of the project. You can find it in the Api & Services, then Credentials page.
![image](https://user-images.githubusercontent.com/41989385/120530547-4dcb5e00-c3e6-11eb-8823-134d72d5d94f.jpeg)


Check the API Keys that the iOS app is there with correct info.
![image](https://user-images.githubusercontent.com/41989385/120530642-72273a80-c3e6-11eb-9376-947b9af18ddf.jpeg)


And also check the OAuth 2.0 Client IDs.
![image](https://user-images.githubusercontent.com/41989385/120530765-92ef9000-c3e6-11eb-8371-a542d784c9c0.jpeg)

Hope this helps.

Also has the remote configured functionality ever worked on iOS with the app or broken since running it?

**Comment by pr-Mais** [comment]
Thanks Yazeed! I just ran it on iOS the past month, the version on App Store isn't the Flutter one.
It works now, I didn't realize I had a different bundle ID between the app and Firebase, so I created a new Firebase App with Flutter iOS bundle ID, this was the problem.

**Comment by pr-Mais** [comment]
Interestingly, it didn't work till I did this, the logs in Xcode indicated that it was failing to lookup the API to fetch, so I tried to check if the app was connecting to internet, and surprisingly it worked with this line added, once removed it doesn't.
I will investigate more but leaving it here if you would like to take a look: https://github.com/pr-Mais/noor/commit/f0ea569f403f9d3d501f303edd461b57cdf5a550
